"""Interval estimates for benchmark aggregates.

Two questions need two intervals (see ``docs/measurement-design.md``):

- ``wilson_interval`` — "how many task-samples passed": a binomial proportion where
  every task counts as one trial regardless of its size.
- ``bootstrap_interval`` — "how much would the route-weighted score move if the task
  list were drawn again": a percentile bootstrap over tasks that keeps the route weights
  and averages each task's sample outcomes.

Both are deterministic for a given seed so a report can be regenerated byte-for-byte.
"""

from __future__ import annotations

import math
import random
from collections.abc import Sequence
from dataclasses import dataclass

DEFAULT_RESAMPLES = 2000
DEFAULT_SEED = 20260902


@dataclass(frozen=True)
class Interval:
    """A point estimate with a two-sided interval at ``confidence``."""

    estimate: float
    low: float
    high: float
    confidence: float = 0.95

    def to_dict(self) -> dict[str, float]:
        return {
            "estimate": self.estimate,
            "low": self.low,
            "high": self.high,
            "confidence": self.confidence,
        }


def _z(confidence: float) -> float:
    if not 0 < confidence < 1:
        raise ValueError(f"confidence must be in (0, 1): {confidence}")
    # Inverse normal CDF via the rational approximation of Acklam (relative error < 1e-9),
    # so the module needs no SciPy.
    p = 1 - (1 - confidence) / 2
    a = (
        -3.969683028665376e01,
        2.209460984245205e02,
        -2.759285104469687e02,
        1.383577518672690e02,
        -3.066479806614716e01,
        2.506628277459239e00,
    )
    b = (
        -5.447609879822406e01,
        1.615858368580409e02,
        -1.556989798598866e02,
        6.680131188771972e01,
        -1.328068155288572e01,
    )
    c = (
        -7.784894002430293e-03,
        -3.223964580411365e-01,
        -2.400758277161838e00,
        -2.549732539343734e00,
        4.374664141464968e00,
        2.938163982698783e00,
    )
    d = (
        7.784695709041462e-03,
        3.224671290700398e-01,
        2.445134137142996e00,
        3.754408661907416e00,
    )
    if p < 0.02425:
        q = math.sqrt(-2 * math.log(p))
        return (((((c[0] * q + c[1]) * q + c[2]) * q + c[3]) * q + c[4]) * q + c[5]) / (
            (((d[0] * q + d[1]) * q + d[2]) * q + d[3]) * q + 1
        )
    if p > 1 - 0.02425:
        q = math.sqrt(-2 * math.log(1 - p))
        return -(((((c[0] * q + c[1]) * q + c[2]) * q + c[3]) * q + c[4]) * q + c[5]) / (
            (((d[0] * q + d[1]) * q + d[2]) * q + d[3]) * q + 1
        )
    q = p - 0.5
    r = q * q
    return (
        (((((a[0] * r + a[1]) * r + a[2]) * r + a[3]) * r + a[4]) * r + a[5])
        * q
        / (((((b[0] * r + b[1]) * r + b[2]) * r + b[3]) * r + b[4]) * r + 1)
    )


def wilson_interval(passed: int, total: int, *, confidence: float = 0.95) -> Interval:
    """Wilson score interval for a binomial proportion; ``total == 0`` spans [0, 1]."""
    if passed < 0 or total < 0 or passed > total:
        raise ValueError(f"invalid counts: passed={passed}, total={total}")
    if total == 0:
        return Interval(estimate=0.0, low=0.0, high=1.0, confidence=confidence)
    z = _z(confidence)
    proportion = passed / total
    denominator = 1 + z * z / total
    centre = (proportion + z * z / (2 * total)) / denominator
    margin = (
        z * math.sqrt(proportion * (1 - proportion) / total + z * z / (4 * total * total))
    ) / denominator
    return Interval(
        estimate=proportion,
        low=max(0.0, centre - margin),
        high=min(1.0, centre + margin),
        confidence=confidence,
    )


def _percentile(sorted_values: Sequence[float], fraction: float) -> float:
    if not sorted_values:
        raise ValueError("no values")
    position = fraction * (len(sorted_values) - 1)
    lower = math.floor(position)
    upper = math.ceil(position)
    if lower == upper:
        return sorted_values[lower]
    weight = position - lower
    return sorted_values[lower] * (1 - weight) + sorted_values[upper] * weight


def weighted_score(task_outcomes: Sequence[Sequence[bool]], weights: Sequence[int]) -> float:
    """Route-weighted score: each task contributes its weight times its sample pass rate."""
    if len(task_outcomes) != len(weights):
        raise ValueError("one weight per task is required")
    total = sum(weights)
    if total <= 0:
        return 0.0
    earned = 0.0
    for outcomes, weight in zip(task_outcomes, weights, strict=True):
        if not outcomes:
            continue
        earned += weight * (sum(1 for passed in outcomes if passed) / len(outcomes))
    return earned / total


def bootstrap_interval(
    task_outcomes: Sequence[Sequence[bool]],
    weights: Sequence[int],
    *,
    confidence: float = 0.95,
    resamples: int = DEFAULT_RESAMPLES,
    seed: int = DEFAULT_SEED,
) -> Interval:
    """Percentile bootstrap of the route-weighted score over tasks.

    Each resample draws tasks with replacement and keeps every drawn task's weight and
    sample outcomes, so the interval reflects "which tasks made the suite" rather than
    the tool's effect.
    """
    if len(task_outcomes) != len(weights):
        raise ValueError("one weight per task is required")
    estimate = weighted_score(task_outcomes, weights)
    count = len(task_outcomes)
    if count == 0 or resamples <= 0:
        return Interval(estimate=estimate, low=estimate, high=estimate, confidence=confidence)
    generator = random.Random(seed)
    scores: list[float] = []
    for _ in range(resamples):
        picks = [generator.randrange(count) for _ in range(count)]
        scores.append(
            weighted_score([task_outcomes[i] for i in picks], [weights[i] for i in picks])
        )
    scores.sort()
    tail = (1 - confidence) / 2
    return Interval(
        estimate=estimate,
        low=_percentile(scores, tail),
        high=_percentile(scores, 1 - tail),
        confidence=confidence,
    )


def paired_difference_interval(
    treatment: Sequence[Sequence[bool]],
    control: Sequence[Sequence[bool]],
    weights: Sequence[int],
    *,
    confidence: float = 0.95,
    resamples: int = DEFAULT_RESAMPLES,
    seed: int = DEFAULT_SEED,
) -> Interval:
    """Bootstrap interval of the route-weighted score difference (treatment - control).

    Tasks are resampled in pairs, so task difficulty cancels and only the arm's effect
    remains: an interval that excludes zero supports a published delta.
    """
    if not len(treatment) == len(control) == len(weights):
        raise ValueError("treatment, control, and weights must align per task")
    estimate = weighted_score(treatment, weights) - weighted_score(control, weights)
    count = len(weights)
    if count == 0 or resamples <= 0:
        return Interval(estimate=estimate, low=estimate, high=estimate, confidence=confidence)
    generator = random.Random(seed)
    differences: list[float] = []
    for _ in range(resamples):
        picks = [generator.randrange(count) for _ in range(count)]
        picked_weights = [weights[i] for i in picks]
        differences.append(
            weighted_score([treatment[i] for i in picks], picked_weights)
            - weighted_score([control[i] for i in picks], picked_weights)
        )
    differences.sort()
    tail = (1 - confidence) / 2
    return Interval(
        estimate=estimate,
        low=_percentile(differences, tail),
        high=_percentile(differences, 1 - tail),
        confidence=confidence,
    )


def paired_numeric_interval(
    treatment: Sequence[float],
    control: Sequence[float],
    *,
    confidence: float = 0.95,
    resamples: int = DEFAULT_RESAMPLES,
    seed: int = DEFAULT_SEED,
) -> Interval:
    """Bootstrap the mean paired numeric difference (treatment - control)."""
    if len(treatment) != len(control):
        raise ValueError("treatment and control values must align")
    if not 0 < confidence < 1:
        raise ValueError(f"confidence must be in (0, 1): {confidence}")
    differences = [left - right for left, right in zip(treatment, control, strict=True)]
    estimate = sum(differences) / len(differences) if differences else 0.0
    if not differences or resamples <= 0:
        return Interval(estimate=estimate, low=estimate, high=estimate, confidence=confidence)
    generator = random.Random(seed)
    means = [
        sum(generator.choice(differences) for _ in differences) / len(differences)
        for _ in range(resamples)
    ]
    means.sort()
    tail = (1 - confidence) / 2
    return Interval(
        estimate=estimate,
        low=_percentile(means, tail),
        high=_percentile(means, 1 - tail),
        confidence=confidence,
    )


__all__ = [
    "DEFAULT_RESAMPLES",
    "DEFAULT_SEED",
    "Interval",
    "bootstrap_interval",
    "paired_difference_interval",
    "paired_numeric_interval",
    "weighted_score",
    "wilson_interval",
]
